### ISSUE TITLE
Prepare for 1.0

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/go-logger#80]
There has been a push to promote this library to versjon 1.0. In order to do that we need to ensure the quality of the library.

```[tasklist]
### Tasks
- [ ] Update user documentation in Inventory
- [ ] Update code documentation of exported functions, structs and interfaces
- [ ] Update maintainer documentation
- [ ] Ensure we are happy with the current state of exported functions, structs and interfaces
- [ ] Delete deprecated functionality
```
